version: "3"

services:
  client:
    build: ./client
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    volumes:
      -./client/src:/app
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "6001:6001"
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
  
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
  middleware:
  controllers:
  routes: